/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QualityAssuranceRouteImport } from './routes/quality-assurance'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsCategoryRouteImport } from './routes/products.$category'
import { Route as CatalogueSlugRouteImport } from './routes/catalogue.$slug'
import { Route as ApplicationsCategoryRouteImport } from './routes/applications.$category'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminProductsRouteImport } from './routes/admin.products'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityAssuranceRoute = QualityAssuranceRouteImport.update({
  id: '/quality-assurance',
  path: '/quality-assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ProductsRoute,
} as any)
const CatalogueSlugRoute = CatalogueSlugRouteImport.update({
  id: '/catalogue/$slug',
  path: '/catalogue/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsCategoryRoute = ApplicationsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ApplicationsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/applications': typeof ApplicationsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quality-assurance': typeof QualityAssuranceRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/applications/$category': typeof ApplicationsCategoryRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quality-assurance': typeof QualityAssuranceRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/applications/$category': typeof ApplicationsCategoryRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/admin': typeof AdminIndexRoute
  '/catalogue': typeof CatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/applications': typeof ApplicationsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quality-assurance': typeof QualityAssuranceRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/applications/$category': typeof ApplicationsCategoryRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/applications'
    | '/contacts'
    | '/login'
    | '/products'
    | '/profile'
    | '/quality-assurance'
    | '/resources'
    | '/services'
    | '/signup'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/resources'
    | '/admin/users'
    | '/applications/$category'
    | '/catalogue/$slug'
    | '/products/$category'
    | '/admin/'
    | '/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/contacts'
    | '/login'
    | '/products'
    | '/profile'
    | '/quality-assurance'
    | '/resources'
    | '/services'
    | '/signup'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/resources'
    | '/admin/users'
    | '/applications/$category'
    | '/catalogue/$slug'
    | '/products/$category'
    | '/admin'
    | '/catalogue'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/applications'
    | '/contacts'
    | '/login'
    | '/products'
    | '/profile'
    | '/quality-assurance'
    | '/resources'
    | '/services'
    | '/signup'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/resources'
    | '/admin/users'
    | '/applications/$category'
    | '/catalogue/$slug'
    | '/products/$category'
    | '/admin/'
    | '/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplicationsRoute: typeof ApplicationsRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  QualityAssuranceRoute: typeof QualityAssuranceRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  CatalogueSlugRoute: typeof CatalogueSlugRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-assurance': {
      id: '/quality-assurance'
      path: '/quality-assurance'
      fullPath: '/quality-assurance'
      preLoaderRoute: typeof QualityAssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/catalogue/$slug': {
      id: '/catalogue/$slug'
      path: '/catalogue/$slug'
      fullPath: '/catalogue/$slug'
      preLoaderRoute: typeof CatalogueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$category': {
      id: '/applications/$category'
      path: '/$category'
      fullPath: '/applications/$category'
      preLoaderRoute: typeof ApplicationsCategoryRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProductsRoute: typeof AdminProductsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProductsRoute: AdminProductsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApplicationsRouteChildren {
  ApplicationsCategoryRoute: typeof ApplicationsCategoryRoute
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsCategoryRoute: ApplicationsCategoryRoute,
}

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
)

interface ProductsRouteChildren {
  ProductsCategoryRoute: typeof ProductsCategoryRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCategoryRoute: ProductsCategoryRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  ContactsRoute: ContactsRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  QualityAssuranceRoute: QualityAssuranceRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  CatalogueSlugRoute: CatalogueSlugRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
